// JavaScript Document


var restaurants = [
  "39759 Nutrition",
	"44 Prime",
	"Arepas Coffee & Bar",
	"BIN 612",
	"Bluto's Greek Tavern",
	"Boardtown Pizza",
	"Brown Bag Prov.",
	"Buffalo Wild Wings",
	"Bulldog Burger Co.",
	"Cater's Market",
	"Central Station Grill",
	"Chick-Fil-A",
	"Dapper Doughnut",
	"Dave's Dark Horse Tavern",
	"Easy Street Brunch Co.",
	"Firehouse Sub",
	"Georgia Blue",
	"Godfather's Pizza",
	"Guadalajara",
	"Harvey's",
	"Jack's Restaurant",
	"Jersey Mikes",
	"Lost Pizza Company",
	"McAlister's Deli",
	"Moe's Original Bar-B-Que",
	"Newk's Eatery",
	"Nine-twentynine Coffee Bar",
	"No Way Jose",
	"Oby's",
	"Papa John's Pizza",
	"Pita Pit",
	"Restaurant Tyler",
	"Rick's Cafe",
	"Rosy Baby",
	"Salsarita's",
	"Slim Chickens",
	"Starkville Cafe",
	"Taste",
	"The Camphouse",
	"The Coffee Depot",
	"The Guest Room",
	"The Little Dooey",
	"Umi Japanese Cuisine",
	"Walk'On's Sport bistreaux",
	"Wendy's",
	"Wingstop",
	"YardBird Bento",
	"Two Brothers",
	
];
